export const GET_PLATFORMS = "GET_PLATFORMS";
export const GET_GENRES = "GET_GENRES";
export const POST_USER = "POST_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_GENRES_FILTER = "GET_GENRES_FILTER"
export const GET_PLATFORMS_FILTER = "GET_PLATFORMS_FILTER"
export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES"
export const QUERY="QUERY"
